name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: TicTacToe_Gruppe_B-jar
          path: target/*.jar